import type { LevelSnapshot } from "@/lib/types";
import { armorClass } from "@/lib/shim-sham/armor";
import { savingThrows } from "@/lib/shim-sham/saves";

type LevelProgression = Omit<LevelSnapshot, "ac" | "fort" | "reflex" | "will">;

/** Level progression from https://gist.github.com/keesey/7ae2c20287b0555a44d3f910eecb4530
 *  Gist vs calculated values: data/progression-gist-issues.md
 */
export const PROGRESSION: LevelProgression[] = [
  {
    level: 1,
    abilities: { STR: 1, DEX: 4, CON: 0, INT: 0, WIS: 1, CHA: 3 },
    maxHp: 18,
    perception: 7,
    classDc: 18,
    landSpeed: 25,
    preciseStrike: 2,
    finisherDice: "2d6",
    notes: ["Panache", "Precise Strike 2", "Battledancer", "Confident Finisher"],
  },
  {
    level: 2,
    abilities: { STR: 1, DEX: 4, CON: 0, INT: 0, WIS: 1, CHA: 3 },
    maxHp: 28,
    perception: 8,
    classDc: 19,
    landSpeed: 25,
    preciseStrike: 2,
    finisherDice: "2d6",
    notes: ["Dirty Trick", "Duelist Dedication", "Quick Draw"],
  },
  {
    level: 3,
    abilities: { STR: 1, DEX: 4, CON: 0, INT: 0, WIS: 1, CHA: 3 },
    maxHp: 41,
    perception: 10,
    classDc: 20,
    landSpeed: 35,
    climbSpeed: 30,
    preciseStrike: 2,
    finisherDice: "2d6",
    notes: [
      "Fortitude Expertise",
      "Toughness",
      "Opportune Riposte",
      "Performance Expert",
      "Acrobatics Expert",
      "Vivacious Speed +10",
      "Advanced Tempweave",
    ],
  },
  {
    level: 4,
    abilities: { STR: 1, DEX: 4, CON: 0, INT: 0, WIS: 1, CHA: 3 },
    maxHp: 52,
    perception: 11,
    classDc: 21,
    landSpeed: 35,
    climbSpeed: 30,
    preciseStrike: 2,
    finisherDice: "2d6",
    notes: ["Slippery Prey", "Leading Dance", "Commercial Force Field"],
  },
  {
    level: 5,
    abilities: { STR: 2, DEX: 4, CON: 1, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 68,
    perception: 12,
    classDc: 22,
    landSpeed: 35,
    flySpeed: 25,
    climbSpeed: 30,
    preciseStrike: 3,
    finisherDice: "3d6",
    notes: ["Climbing Claws", "Weapon Expertise", "Athletics Trained"],
  },
  {
    level: 6,
    abilities: { STR: 2, DEX: 4, CON: 1, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 80,
    perception: 11,
    classDc: 22,
    landSpeed: 30,
    flySpeed: 25,
    climbSpeed: 30,
    preciseStrike: 3,
    finisherDice: "3d6",
    notes: ["Combat Climber", "Dueling Parry"],
  },
  {
    level: 7,
    abilities: { STR: 2, DEX: 4, CON: 1, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 92,
    perception: 13,
    classDc: 23,
    landSpeed: 35,
    flySpeed: 30,
    climbSpeed: 35,
    preciseStrike: 3,
    finisherDice: "3d6",
    notes: [
      "Confident Evasion",
      "Feather Step",
      "Performance Master",
      "Acrobatics Master",
      "Vivacious Speed +15",
      "Weapon Specialization",
    ],
  },
  {
    level: 8,
    abilities: { STR: 2, DEX: 4, CON: 1, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 104,
    perception: 14,
    classDc: 24,
    landSpeed: 35,
    flySpeed: 30,
    climbSpeed: 35,
    preciseStrike: 3,
    finisherDice: "3d6",
    notes: ["Quick Jump", "Charmed Life"],
  },
  {
    level: 9,
    abilities: { STR: 2, DEX: 4, CON: 1, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 116,
    perception: 15,
    classDc: 25,
    landSpeed: 35,
    flySpeed: 30,
    climbSpeed: 35,
    preciseStrike: 4,
    finisherDice: "4d6",
    notes: ["Meyel's Melody", "Exemplary Finisher (Step)", "Intimidation Expert"],
  },
  {
    level: 10,
    abilities: { STR: 3, DEX: 5, CON: 2, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 138,
    perception: 16,
    classDc: 26,
    landSpeed: 40,
    flySpeed: 35,
    climbSpeed: 40,
    preciseStrike: 4,
    finisherDice: "4d6",
    notes: ["Intimidating Prowess", "Dueling Riposte"],
  },
  {
    level: 11,
    abilities: { STR: 3, DEX: 5, CON: 2, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 151,
    perception: 19,
    classDc: 27,
    landSpeed: 45,
    flySpeed: 40,
    climbSpeed: 45,
    preciseStrike: 4,
    finisherDice: "4d6",
    notes: [
      "Continuous Flair",
      "Incredible Scout",
      "Perception Mastery",
      "Thievery Expert",
      "Vivacious Speed +20",
    ],
  },
  {
    level: 12,
    abilities: { STR: 3, DEX: 5, CON: 2, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 164,
    perception: 20,
    classDc: 28,
    landSpeed: 45,
    flySpeed: 40,
    climbSpeed: 45,
    preciseStrike: 4,
    finisherDice: "4d6",
    notes: ["Tumbling Theft", "Mobile Finisher"],
  },
  {
    level: 13,
    abilities: { STR: 3, DEX: 5, CON: 2, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 177,
    perception: 21,
    classDc: 29,
    landSpeed: 45,
    flySpeed: 40,
    climbSpeed: 45,
    preciseStrike: 5,
    finisherDice: "5d6",
    notes: [
      "Predatory (Claws)",
      "Assured Evasion",
      "Light Armor Expertise",
      "Athletics Expert",
      "Weapon Mastery",
    ],
  },
  {
    level: 14,
    abilities: { STR: 3, DEX: 5, CON: 2, INT: 0, WIS: 1, CHA: 4 },
    maxHp: 190,
    perception: 22,
    classDc: 30,
    landSpeed: 45,
    flySpeed: 40,
    climbSpeed: 45,
    preciseStrike: 5,
    finisherDice: "5d6",
    notes: ["Virtuosic Performer", "Selfless Parry"],
  },
  {
    level: 15,
    abilities: { STR: 4, DEX: 5, CON: 3, INT: 1, WIS: 1, CHA: 5 },
    maxHp: 218,
    perception: 23,
    classDc: 31,
    landSpeed: 50,
    flySpeed: 45,
    climbSpeed: 50,
    preciseStrike: 5,
    finisherDice: "5d6",
    notes: [
      "Incredible Initiative",
      "Greater Weapon Specialization",
      "Keen Flair",
      "Acrobatics Legendary",
      "Performance Legendary",
      "Vivacious Speed +25",
      "Language: Diabolic",
    ],
  },
];

function withDerivedStats(entry: LevelProgression): LevelSnapshot {
  return {
    ...entry,
    ac: armorClass(entry.abilities.DEX, entry.level),
    ...savingThrows(entry.abilities, entry.level),
  };
}

export function getLevelSnapshot(level: number): LevelSnapshot | undefined {
  const entry = PROGRESSION.find((item) => item.level === level);
  return entry ? withDerivedStats(entry) : undefined;
}

export function getNextLevelSnapshot(level: number): LevelSnapshot | undefined {
  const entry = PROGRESSION.find((item) => item.level === level + 1);
  return entry ? withDerivedStats(entry) : undefined;
}
